AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a CodePipeline role and policy.

Resources:
# IAM
  CodePipelinePolicy:
    Type: AWS::IAM::Policy
    DependsOn: CodePipelineRole
    Properties:
      PolicyName: CFNUsers
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - appconfig:StartDeployment
              - appconfig:StopDeployment
              - appconfig:GetDeployment
            Resource: '*'
          - Effect: Allow
            Action:
              - states:DescribeExecution
              - states:DescribeStateMachine
              - states:StartExecution
              - ecr:DescribeImages
              - cloudformation:*
              - cloudformation:ValidateTemplate
              - servicecatalog:ListProvisioningArtifacts
              - servicecatalog:CreateProvisioningArtifact
              - servicecatalog:DescribeProvisioningArtifact
              - servicecatalog:DeleteProvisioningArtifact
              - servicecatalog:UpdateProduct
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
              - lambda:InvokeFunction
              - lambda:ListFunctions
              - elasticbeanstalk:*
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - rds:*
              - sqs:*
              - ecs:*
              - codedeploy:CreateDeployment
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
              - codestar-connections:UseConnection
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetRepository
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
            Resource: '*'
          - Action:
              - iam:PassRole
            Resource: '*'
            Effect: Allow
          - Action:
              - sts:AssumeRole
            Resource: '*'
            Effect: Allow
          - Effect: Allow
            Resource: "*"
            # Condition:
            #   ForAnyValue:StringLike:
            #     kms:ResourceAliases:
            #       - !Ref codepipelineKeyAlias
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
      Roles:
        - !Ref 'CodePipelineRole'

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: !Sub 'dg-cicd-codepipeline'