AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an ECS, Service and taskdefinition instance for the IdeaHub project.

Parameters:
  SecurityGroup:
    Description: The security group for the EC2 instance
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-04b25b88d0a3ba979
    ConstraintDescription: must be a valid security group ID.

Resources:      
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ideahub-ecs-cluster

  IdeaHubTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ideahub-service-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: arn:aws:iam::925413096657:role/ECS-Tasks-Role
      ContainerDefinitions:
        - Name: ideahub-django-container
          Image: 925413096657.dkr.ecr.ap-south-1.amazonaws.com/ideahub-image:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
          Environment:
            - Name: DB_PORT
              Value: "3306"
            - Name: DB_HOST
              Value: 13.235.50.125
            - Name: DB_USER
              Value: "{{resolve:secretsmanager:dev/ideaHub/Mysql:SecretString:username}}"
            - Name: DB_PASSWORD
              Value: "{{resolve:secretsmanager:dev/ideaHub/Mysql:SecretString:password}}"
            - Name: DB_NAME
              Value: "{{resolve:secretsmanager:dev/ideaHub/Mysql:SecretString:dbname}}"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/ideahub
              awslogs-region: ap-south-1
              awslogs-stream-prefix: ideahub-django-container

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/ideahub
      RetentionInDays: 14

  IdeaHubService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref IdeaHubTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-0e34464d85af942ba
            - subnet-010c62db980da470c
            - subnet-0f72574fceff03451
          SecurityGroups:
            - !Ref SecurityGroup
          AssignPublicIp: ENABLED

